### ISSUE TITLE
Dynamic Linking Error: Win32 error 126

### ISSUE THREAD

**Issue by anshtiwari314** [dgurkaynak/nodeshout#15]
I cloned the repo. when try to run this project it gives me  
Error: Dynamic Linking Error: Win32 error 126
    at new DynamicLibrary (C:\Users\anuj\Desktop\testing\nodeshout\node_modules\ffi-napi\lib\dynamic_library.js:75:11)
    at Object.Library (C:\Users\anuj\Desktop\testing\nodeshout\node_modules\ffi-napi\lib\library.js:47:10)
    at Object.<anonymous> (C:\Users\anuj\Desktop\testing\nodeshout\src\libshout.js:11:23)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\Users\anuj\Desktop\testing\nodeshout\src\index.js:1:18)
![git-issue](https://github.com/dgurkaynak/nodeshout/assets/68491888/1b283389-9695-40ad-9249-2c08142f6d67)

**Comment by cabfile** [comment]
hey there. i ran into the same issue, but fortunately found a solution

first go [here](https://github.com/xiph/Icecast-libshout/issues/9#issuecomment-425373166) to download some pre-built dlls
then simply unzip them in the same directory as the js file you're trying to run
and rename libshout-3.dll to libshout.dll
hope this helps
