### ISSUE TITLE
Cannot start stream with external host

### ISSUE THREAD

**Issue by EwanRoycroft** [dgurkaynak/nodeshout#7]
I am having trouble connecting connecting nodeshout to external Icecast servers. When connecting to localhost, it works perfectly; but if I put in the hostname for an Icecast server on another computer, the stream fails to start. 

The program stops when `shout.open()` invokes `ffi_call()` in the FFI `proxy` function. There is no console output, it just hangs.

Here's my stack trace:
```
Trace
    at eval (eval at proxy (./node_modules/ffi/lib/_foreign_function.js:59:5), <anonymous>:1:9)
    at Object.proxy [as shout_open] (./node_modules/ffi/lib/_foreign_function.js:59:5)
    at shoutT.open (./node_modules/nodeshout/src/shoutT.js:185:21)
    at Object.<anonymous> (./index.js:76:7)
    at Module._compile (internal/modules/cjs/loader.js:686:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
```

**Comment by TriPSs** [comment]
Could you give an example of the hostname that does not work and how you set it?

**Comment by EwanRoycroft** [comment]
I've tried both "149.255.59.3" and "streaming03.zfast.co.uk"; I've also tried putting "http://" at the start with no joy. Another computer on the same network, running [Sonos 4](http://www.burnill.co.uk/), has no trouble connecting to the same server.

**Comment by EwanRoycroft** [comment]
Tried it on a third network now an it's working fine. I assume this must be a proxy/firewall issue.

**Comment by dgurkaynak** [comment]
I've just tried with a remote icecast server in my local network (`192.168.x.x`), and I can confirm it's working 👍
